const customers = [
  {
    id: '326253a4-9f42-4c7d-aab5-0d2425c146f0',
    firstName: 'Ayomikun',
    lastName: 'Olorunda',
    middleName: 'Ugliness',
    bvn: '22343234567',
    address: 'Live in the middle of nowhere.',
    email: 'olorundayomikun90@gmail.com',
    gender: 'male',
    dob: new Date(),
    phone: '08124444173',
    cscs: '1232343',
    chn: '13425AL',
    cscsRef: '222',
    cscsVerified: true,
    cscsRequestStatus: 'requested',
    cscsRequestFailureReason: '',
    role: 'customer',
    verified: true,
    status: 'active',
    zanibalId: '',
    image: '',
    website: 'https://www.youtube.com',
    twitter: '',
    facebook: '',
    linkedIn: '',
    youtube: 'https://www.youtube.com/AyCx',
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = {
  customers,
};
